import type { Bilingual, Lesson, Track, TrackId } from './types'

const bi = (ar: string, en: string): Bilingual => ({ ar, en })
const lesson = (
  id: string, titleAr: string, titleEn: string, duration: number, objectiveAr: string, objectiveEn: string,
  conceptAr: string, conceptEn: string, code: string, questionAr: string, questionEn: string,
  choices: [string, string][], answer: number, explanationAr: string, explanationEn: string,
): Lesson => ({
  id, title: bi(titleAr, titleEn), duration, objective: bi(objectiveAr, objectiveEn), concept: bi(conceptAr, conceptEn), code,
  challenge: { question: bi(questionAr, questionEn), choices: choices.map(([ar, en]) => bi(ar, en)), answer, explanation: bi(explanationAr, explanationEn) },
})

const t = (id: TrackId, ar: string, en: string, summaryAr: string, summaryEn: string, color: string, lessons: Lesson[]): Track => ({
  id, title: bi(ar, en), summary: bi(summaryAr, summaryEn), color, level: bi('من المبتدئ إلى جاهز للمشاريع', 'Beginner to project-ready'), lessons,
})

export const tracks: Track[] = [
  t('python', 'أساسيات Python', 'Python Foundations', 'ابنِ منطقك البرمجي ومشروع أدوات بسيط.', 'Build programming logic and a practical starter tool.', '#7c5cff', [
    lesson('py-1', 'كيف يفكر البرنامج؟', 'How programs think', 12, 'تمييز البيانات والتعليمات والمخرجات.', 'Distinguish data, instructions, and outputs.', 'البرنامج سلسلة تعليمات دقيقة؛ ابدأ بمدخلات واضحة ثم اختبر النتيجة.', 'A program is a precise sequence of instructions; start with clear inputs and test the result.', 'name = "Ali"\nprint(f"Welcome, {name}")', 'ما وظيفة print؟', 'What does print do?', [['تخزن البيانات', 'Stores data'], ['تعرض قيمة للمستخدم', 'Shows a value to the user'], ['تكرّر الكود', 'Repeats code'], ['تنشئ ملفاً', 'Creates a file']], 1, 'print تعرض قيماً أو نصوصاً في المخرجات.', 'print shows values or text in the output.'),
    lesson('py-2', 'المتغيرات والأنواع', 'Variables and types', 16, 'تخزين القيم واختيار النوع المناسب.', 'Store values and select the right type.', 'استخدم أسماء تصف المعنى؛ النصوص بين علامات اقتباس والأرقام لا تحتاجها.', 'Use names that describe meaning; strings use quotes while numbers do not.', 'student = "Zahraa"\nhours = 3\nactive = True', 'أي قيمة تمثل Boolean؟', 'Which value is Boolean?', [['"3"', '"3"'], ['3', '3'], ['True', 'True'], ['3.0', '3.0']], 2, 'True وFalse قيمتان منطقيتان.', 'True and False are Boolean values.'),
    lesson('py-3', 'الشروط والقرارات', 'Conditions and decisions', 18, 'تطبيق if لاتخاذ قرار واضح.', 'Apply if to make a clear decision.', 'المقارنات تعيد True أو False، وتتحكم if في المسار الذي ينفذ.', 'Comparisons return True or False, and if controls which path runs.', 'score = 82\nif score >= 50:\n    print("Passed")\nelse:\n    print("Try again")', 'متى ينفذ else؟', 'When does else run?', [['دائماً', 'Always'], ['عندما يكون الشرط False', 'When the condition is False'], ['قبل if', 'Before if'], ['بعد print فقط', 'After print only']], 1, 'else هو المسار البديل عندما لا يتحقق الشرط.', 'else is the alternative path when the condition is not met.'),
    lesson('py-4', 'الحلقات والقوائم', 'Loops and lists', 20, 'التعامل مع مجموعة عناصر دون تكرار يدوي.', 'Work with a group of items without manual repetition.', 'القائمة تجمع قيماً مرتبة، وfor تمر على كل عنصر فيها.', 'A list groups ordered values, and for visits every item.', 'skills = ["Python", "Git", "SQL"]\nfor skill in skills:\n    print(skill)', 'ما الذي تمثله skill داخل الحلقة؟', 'What does skill represent inside the loop?', [['كل القائمة', 'The entire list'], ['العنصر الحالي', 'The current item'], ['عدد العناصر', 'The item count'], ['اسم الحلقة', 'The loop name']], 1, 'في كل دورة تحمل skill عنصراً واحداً من القائمة.', 'On each iteration, skill holds one item from the list.'),
    lesson('py-5', 'الدوال وإعادة الاستخدام', 'Functions and reuse', 22, 'إنشاء دالة صغيرة قابلة للاختبار.', 'Create a small testable function.', 'الدالة تجمع سلوكاً له اسم ومدخلات، وتمنع نسخ المنطق في أماكن متعددة.', 'A function groups named behavior and inputs, preventing duplicated logic.', 'def welcome(name):\n    return f"Welcome, {name}"\n\nprint(welcome("Sara"))', 'لماذا نستخدم return؟', 'Why use return?', [['لإيقاف الإنترنت', 'To stop the internet'], ['لإرجاع نتيجة من الدالة', 'To send a result back from a function'], ['لطباعة كل شيء', 'To print everything'], ['لإنشاء قائمة', 'To create a list']], 1, 'return تعيد قيمة ليستخدمها جزء آخر من البرنامج.', 'return sends a value back for another part of the program to use.'),
    lesson('py-6', 'مشروع: متعقب دراسة', 'Project: study tracker', 28, 'تجميع الأساسيات في أداة دراسة صغيرة.', 'Combine the fundamentals in a small study tool.', 'المشروع الجيد يقسم المشكلة إلى بيانات ودوال وشروط ومخرجات قابلة للتحقق.', 'A good project separates the problem into data, functions, conditions, and verifiable output.', 'minutes = [25, 40, 30]\ntotal = sum(minutes)\nprint(f"Study minutes: {total}")', 'ما الناتج الصحيح لـ total؟', 'What is the correct value of total?', [['25', '25'], ['40', '40'], ['95', '95'], ['3', '3']], 2, 'sum يجمع عناصر قائمة الأرقام: 25 + 40 + 30 = 95.', 'sum adds numeric list items: 25 + 40 + 30 = 95.'),
  ]),
  t('web', 'HTML وCSS', 'HTML & CSS', 'صمّم واجهات ويب دلالية ومتجاوبة ويمكن الوصول إليها.', 'Design semantic, responsive, accessible web interfaces.', '#00b8a9', [
    lesson('web-1', 'هيكل صفحة الويب', 'The web page structure', 14, 'فهم دور HTML في وصف المحتوى.', 'Understand HTML’s role in describing content.', 'HTML يعبّر عن بنية ومعنى المحتوى، وليس عن الألوان والتخطيط.', 'HTML expresses content structure and meaning, not colors and layout.', '<main>\n  <h1>My learning plan</h1>\n  <p>One lesson today.</p>\n</main>', 'أي عنصر هو العنوان الرئيسي؟', 'Which element is the main heading?', [['main', 'main'], ['h1', 'h1'], ['p', 'p'], ['body', 'body']], 1, 'استخدم h1 للعنوان الرئيسي الفريد للصفحة.', 'Use h1 for the page’s unique main heading.'),
    lesson('web-2', 'الدلالة وإتاحة الوصول', 'Semantics and accessibility', 18, 'اختيار عناصر HTML ذات المعنى الصحيح.', 'Choose HTML elements with the right meaning.', 'استعمال button وnav وlabel الصحيح يجعل الواجهة أفضل للمستخدمين وتقنيات المساعدة.', 'Using the correct button, nav, and label improves the interface for people and assistive technologies.', '<button type="button">Save progress</button>\n<nav aria-label="Lesson navigation">...</nav>', 'متى تفضّل button على div؟', 'When should you prefer button over div?', [['لعنصر تفاعلي ينفذ إجراء', 'For an interactive element that performs an action'], ['للعنوان فقط', 'For a heading only'], ['لصورة فقط', 'For an image only'], ['لا فرق', 'There is no difference']], 0, 'button يحمل سلوكاً دلالياً ويدعم لوحة المفاتيح افتراضياً.', 'button carries semantic behavior and supports keyboards by default.'),
    lesson('web-3', 'أساسيات CSS', 'CSS foundations', 18, 'تطبيق أنماط قابلة للصيانة على مكوّن.', 'Apply maintainable styles to a component.', 'اجعل CSS يصف المظهر؛ ابدأ بمقاسات ومسافات وألوان متسقة.', 'Let CSS describe appearance; start with consistent sizing, spacing, and colors.', '.card {\n  padding: 1rem;\n  border-radius: 12px;\n  background: #ffffff;\n}', 'أي خاصية تضيف المساحة داخل البطاقة؟', 'Which property adds space inside the card?', [['margin', 'margin'], ['padding', 'padding'], ['color', 'color'], ['display', 'display']], 1, 'padding هي المسافة بين المحتوى وحدود العنصر.', 'padding is the space between content and an element’s border.'),
    lesson('web-4', 'Flexbox للتخطيط', 'Layout with Flexbox', 22, 'ترتيب عناصر الواجهة بمرونة.', 'Arrange interface elements flexibly.', 'Flexbox مناسب لمحور واحد مثل صف الأزرار أو عمود بطاقة المحتوى.', 'Flexbox is ideal for one axis, such as a button row or a content-card column.', '.actions {\n  display: flex;\n  gap: 0.75rem;\n  align-items: center;\n}', 'ما الذي ينشئ مساحة بين العناصر؟', 'What creates space between items?', [['gap', 'gap'], ['color', 'color'], ['font', 'font'], ['position', 'position']], 0, 'gap يضيف فراغاً منظماً بين عناصر flex أو grid.', 'gap adds consistent space between flex or grid items.'),
    lesson('web-5', 'تصميم متجاوب', 'Responsive design', 22, 'تكييف الواجهة مع الشاشات الصغيرة.', 'Adapt an interface for smaller screens.', 'ابدأ من الهاتف ثم أضف تحسينات للشاشات الأوسع عبر media queries.', 'Start with mobile, then enhance wider layouts with media queries.', '.grid { display: grid; grid-template-columns: 1fr; }\n@media (min-width: 800px) {\n  .grid { grid-template-columns: repeat(3, 1fr); }\n}', 'متى تصبح الشبكة ثلاثة أعمدة؟', 'When does the grid become three columns?', [['عند 800px أو أكثر', 'At 800px or wider'], ['دائماً', 'Always'], ['عند الطباعة', 'When printing'], ['عند النقر', 'When clicked']], 0, 'شرط min-width يطبّق النمط عند بلوغ العرض المحدد.', 'min-width applies a style at or above the specified width.'),
    lesson('web-6', 'مشروع: صفحة Portfolio', 'Project: portfolio page', 30, 'بناء صفحة تعريف قابلة للنشر.', 'Build a publishable introduction page.', 'قسّم الصفحة إلى header وmain وsections ذات عناوين، ثم اجعل كل رابط واضح الهدف.', 'Split the page into header, main, and headed sections, then make every link’s purpose clear.', '<section aria-labelledby="projects">\n  <h2 id="projects">Projects</h2>\n  <a href="https://github.com/">View source</a>\n</section>', 'لماذا يستخدم aria-labelledby هنا؟', 'Why use aria-labelledby here?', [['لربط القسم بعنوانه', 'To associate the section with its heading'], ['لتغيير اللون', 'To change color'], ['لتشغيل JavaScript', 'To run JavaScript'], ['لإخفاء القسم', 'To hide the section']], 0, 'يربط aria-labelledby القسم بعنوان مفهوم لقارئات الشاشة.', 'aria-labelledby connects the section to a meaningful screen-reader heading.'),
  ]),
  t('javascript', 'JavaScript', 'JavaScript', 'أضف التفاعل والمنطق إلى واجهات الويب.', 'Add interaction and logic to web interfaces.', '#f7b801', [
    lesson('js-1', 'القيم والمتغيرات', 'Values and variables', 15, 'استخدام const وlet بوضوح.', 'Use const and let clearly.', 'استخدم const للقيم التي لا ستتغير، وlet للحالة التي تتغير.', 'Use const for values that will not change and let for changing state.', 'const course = "JavaScript"\nlet completed = 0\ncompleted += 1', 'أي متغير يمكن تحديثه هنا؟', 'Which variable can be updated here?', [['course', 'course'], ['completed', 'completed'], ['كلاهما', 'Both'], ['لا واحد', 'Neither']], 1, 'let يسمح بإعادة الإسناد، بينما const لا يسمح بذلك.', 'let allows reassignment; const does not.'),
    lesson('js-2', 'الدوال والأحداث', 'Functions and events', 20, 'ربط فعل المستخدم بدالة صغيرة.', 'Connect a user action to a small function.', 'event listener يستمع للفعل ثم يستدعي دالة واضحة المسؤولية.', 'An event listener listens for an action, then calls a clearly scoped function.', 'const button = document.querySelector("button")\nbutton?.addEventListener("click", () => {\n  console.log("Lesson started")\n})', 'متى ينفذ console.log؟', 'When does console.log run?', [['عند تحميل الصفحة فقط', 'Only on page load'], ['عند نقر الزر', 'When the button is clicked'], ['كل ثانية', 'Every second'], ['لا ينفذ', 'It never runs']], 1, 'مستمع click ينفذ الدالة بعد نقر المستخدم.', 'The click listener runs the function after the user clicks.'),
    lesson('js-3', 'المصفوفات والكائنات', 'Arrays and objects', 20, 'تمثيل مجموعة وكيان ببيانات منظمة.', 'Represent a collection and an entity with structured data.', 'المصفوفة لقائمة عناصر، والكائن لخصائص عنصر واحد.', 'An array is for a list of items; an object is for properties of one item.', 'const learner = { name: "Noor", xp: 120 }\nconst tracks = ["Python", "Web"]\nconsole.log(learner.xp)', 'كيف نصل إلى XP للطالب؟', 'How do we access the learner XP?', [['learner[xp]', 'learner[xp]'], ['learner.xp', 'learner.xp'], ['tracks.xp', 'tracks.xp'], ['xp.learner', 'xp.learner']], 1, 'dot notation تصل إلى خاصية مسماة داخل الكائن.', 'Dot notation accesses a named object property.'),
    lesson('js-4', 'التعامل مع DOM', 'Working with the DOM', 22, 'تحديث جزء محدد من الصفحة بأمان.', 'Update a specific part of the page safely.', 'DOM هو تمثيل الصفحة في المتصفح؛ اختر عناصر محددة وتحقق من وجودها قبل الاستخدام.', 'The DOM is the browser’s page representation; select specific elements and check they exist before use.', 'const status = document.querySelector("#status")\nif (status) status.textContent = "Complete"', 'ما الذي يتغير في المثال؟', 'What changes in this example?', [['عنوان المتصفح', 'Browser title'], ['نص العنصر status', 'The status element text'], ['عنوان URL', 'The URL'], ['ملف CSS', 'The CSS file']], 1, 'textContent يغيّر النص المعروض داخل العنصر.', 'textContent changes the text displayed inside the element.'),
    lesson('js-5', 'التدفق غير المتزامن', 'Asynchronous flow', 24, 'فهم await دون حجب الواجهة.', 'Understand await without blocking the interface.', 'العمليات البطيئة مثل الشبكة تحتاج حالة تحميل ونجاح وخطأ واضحة.', 'Slow work like networking needs clear loading, success, and error states.', 'async function loadProfile() {\n  const response = await fetch("/profile.json")\n  return response.json()\n}', 'ماذا ينتظر await؟', 'What does await wait for?', [['الاستجابة قبل المتابعة', 'The response before continuing'], ['تغيير اللون', 'A color change'], ['نقر الزر', 'A button click'], ['إيقاف الصفحة', 'Stopping the page']], 0, 'await تنتظر اكتمال Promise داخل دالة async.', 'await waits for a Promise inside an async function.'),
    lesson('js-6', 'مشروع: قائمة مهام', 'Project: task list', 30, 'تصميم منطق حالة صغير وواجهته.', 'Design a small state model and interface.', 'افصل البيانات عن العرض: حدث يغير الحالة، ثم دالة تعيد رسم النتيجة.', 'Separate data from display: an event changes state, then a function renders the result.', 'const tasks = ["Read", "Build"]\nconst completed = tasks.filter((task) => task !== "Build")\nconsole.log(completed)', 'كم عنصراً في completed؟', 'How many items are in completed?', [['0', '0'], ['1', '1'], ['2', '2'], ['3', '3']], 1, 'filter يعيد العناصر التي تحقق الشرط، وهنا Read فقط.', 'filter returns items that meet the condition—only Read here.'),
  ]),
  t('git', 'Git وGitHub', 'Git & GitHub', 'نظّم تاريخ الكود وانشر مشاريع قابلة للمراجعة.', 'Organize code history and publish reviewable projects.', '#f05033', [
    lesson('git-1', 'فكرة التحكم بالإصدارات', 'Version control mindset', 12, 'فهم الـcommit كسجل قابل للرجوع.', 'Understand a commit as a reversible record.', 'Git يسجل تغييرات ذات معنى، وليس مجرد نسخ عشوائية من الملفات.', 'Git records meaningful changes instead of random file copies.', 'git status\ngit add src/App.tsx\ngit commit -m "feat: add lesson view"', 'ما الذي يصفه commit الجيد؟', 'What does a good commit describe?', [['تغييراً محدداً', 'A specific change'], ['كل المشروع دائماً', 'The entire project always'], ['اسم المستخدم', 'The username'], ['لون الموقع', 'The site color']], 0, 'رسالة الـcommit تشرح تغييراً صغيراً واضحاً.', 'A commit message explains one clear, small change.'),
    lesson('git-2', 'الـbranch ومساحة العمل', 'Branches and workspace', 18, 'استخدام فرع لتجربة تحسين مستقل.', 'Use a branch for an isolated improvement.', 'الفرع مساحة عمل لتغيير موضوع واحد دون إرباك الفرع الرئيسي.', 'A branch is a workspace for one change without disrupting the main branch.', 'git switch -c feat/profile-card\n# make one focused change\ngit status', 'لماذا ننشئ branch؟', 'Why create a branch?', [['لتجربة تغيير مستقل', 'To work on an isolated change'], ['لحذف Git', 'To delete Git'], ['لتشغيل الموقع', 'To run the site'], ['لتبديل اللغة', 'To change language']], 0, 'الفروع تجعل التغييرات قابلة للمراجعة والدمج بأمان.', 'Branches make changes reviewable and safer to merge.'),
    lesson('git-3', 'README مهني', 'A professional README', 16, 'كتابة مدخل واضح للمشروع.', 'Write a clear project entry point.', 'README يشرح الهدف وطريقة التشغيل والميزات والحدود وروابط النشر.', 'A README explains purpose, setup, features, boundaries, and live links.', '# Project name\n\n> One-sentence value statement.\n\n## Run locally\n## Features\n## License', 'ما أول شيء يجب أن يفهمه الزائر؟', 'What should a visitor understand first?', [['قيمة المشروع وهدفه', 'The project value and purpose'], ['لون المحرر', 'Editor color'], ['كلمة المرور', 'A password'], ['اسم الفرع فقط', 'Only the branch name']], 0, 'ابدأ برسالة واضحة عن ما يحلّه المشروع ومن يستفيد منه.', 'Start with a clear message about what the project solves and who benefits.'),
    lesson('git-4', 'Pull Request كمراجعة', 'Pull requests as review', 20, 'وصف التغيير واختباره قبل الدمج.', 'Describe and test a change before merging.', 'Pull Request جيد يشرح السياق والتغيير والاختبارات والمخاطر المعروفة.', 'A good pull request explains context, changes, tests, and known risks.', '## Summary\n- Adds lesson completion state\n\n## Validation\n- pnpm test\n- pnpm build', 'ما فائدة قسم Validation؟', 'What is the purpose of Validation?', [['إثبات ما تم فحصه', 'To show what was checked'], ['إخفاء الكود', 'To hide code'], ['تغيير الترخيص', 'To change the license'], ['توليد كلمة مرور', 'To generate a password']], 0, 'يوضح للمراجع كيف تحقق صاحب التغيير من النتيجة.', 'It shows reviewers how the author verified the result.'),
    lesson('git-5', 'النشر عبر GitHub Pages', 'Deploying with GitHub Pages', 22, 'فهم فرق البناء عن النشر.', 'Understand the difference between build and deployment.', 'البناء ينتج ملفات ثابتة؛ النشر يجعلها متاحة من رابط عام.', 'Build produces static files; deployment makes them available at a public URL.', 'pnpm build\n# dist/ contains the production files\n# GitHub Actions publishes them to Pages', 'أين توجد ملفات الإنتاج بعد البناء؟', 'Where are production files after building?', [['src/', 'src/'], ['dist/', 'dist/'], ['node_modules/', 'node_modules/'], ['.git/', '.git/']], 1, 'Vite يضع نتيجة الإنتاج في dist افتراضياً.', 'Vite places production output in dist by default.'),
    lesson('git-6', 'مشروع: إطلاق مستودع', 'Project: repository launch', 28, 'تجهيز مشروع عام قابل للمشاركة.', 'Prepare a shareable public project.', 'الإطلاق المهني يجمع README، ترخيصاً، سياسة أمن، اختبارات، ورابطاً حياً.', 'A professional launch brings together a README, license, security policy, tests, and a live link.', 'git add .\ngit commit -m "feat: publish project foundation"\ngit push origin main', 'ما الإجراء الذي يرسل التغييرات إلى GitHub؟', 'Which command sends changes to GitHub?', [['git add', 'git add'], ['git commit', 'git commit'], ['git push', 'git push'], ['git status', 'git status']], 2, 'git push يرسل الـcommits المحلية إلى المستودع البعيد.', 'git push sends local commits to the remote repository.'),
  ]),
  t('sql', 'SQL وقواعد البيانات', 'SQL & Databases', 'تعلم الاستعلامات المنظمة والتفكير في البيانات.', 'Learn structured queries and data thinking.', '#30a4db', [
    lesson('sql-1', 'الجداول والصفوف', 'Tables and rows', 14, 'تمييز الجدول عن الصف والعمود.', 'Distinguish tables, rows, and columns.', 'الجدول يمثل كياناً مثل learners، والصف سجل واحد، والعمود خاصية.', 'A table represents an entity like learners; a row is one record and a column is one property.', 'CREATE TABLE learners (\n  id INTEGER PRIMARY KEY,\n  name TEXT NOT NULL\n);', 'ما الذي يمثله name؟', 'What does name represent?', [['جدولاً', 'A table'], ['عموداً', 'A column'], ['قاعدة بيانات كاملة', 'A full database'], ['استعلام حذف', 'A delete query']], 1, 'name عمود يخزن خاصية الاسم لكل سجل.', 'name is a column that stores the name property for each record.'),
    lesson('sql-2', 'قراءة البيانات بـ SELECT', 'Reading data with SELECT', 18, 'قراءة الحقول التي تحتاجها فقط.', 'Read only the fields you need.', 'ابدأ باستعلامات محددة بدلاً من SELECT * كي تكون النتيجة أوضح وأقل عرضة للأخطاء.', 'Start with specific queries rather than SELECT * so results are clearer and less error-prone.', 'SELECT name, xp\nFROM learners\nWHERE xp >= 100;', 'ما الذي يفعله WHERE؟', 'What does WHERE do?', [['يرتب الأعمدة', 'Orders columns'], ['يصفّي الصفوف', 'Filters rows'], ['ينشئ جدولاً', 'Creates a table'], ['يحذف قاعدة البيانات', 'Deletes the database']], 1, 'WHERE يحدد أي الصفوف تدخل في النتيجة.', 'WHERE specifies which rows appear in the result.'),
    lesson('sql-3', 'إضافة وتحديث البيانات', 'Adding and updating data', 20, 'التفريق بين INSERT وUPDATE.', 'Differentiate INSERT from UPDATE.', 'INSERT يضيف سجلاً جديداً؛ UPDATE يغير سجلاً موجوداً مع شرط واضح.', 'INSERT adds a new record; UPDATE changes an existing record with a clear condition.', 'UPDATE learners\nSET xp = 140\nWHERE id = 7;', 'لماذا يجب أن يتضمن UPDATE شرطاً؟', 'Why should an UPDATE include a condition?', [['لتجنب تعديل كل الصفوف', 'To avoid changing every row'], ['لزيادة السرعة فقط', 'For speed only'], ['لإنشاء جدول', 'To create a table'], ['لا حاجة لشرط', 'No condition is needed']], 0, 'شرط WHERE يحصر التعديل في السجل المقصود.', 'A WHERE condition limits the change to the intended record.'),
    lesson('sql-4', 'الربط بين الجداول', 'Joining tables', 24, 'دمج بيانات مرتبطة دون تكرار غير ضروري.', 'Combine related data without unnecessary duplication.', 'المفاتيح تربط الكيانات؛ JOIN يعرض بيانات متصلة من جدولين.', 'Keys connect entities; JOIN presents related data from two tables.', 'SELECT learners.name, projects.title\nFROM learners\nJOIN projects ON projects.learner_id = learners.id;', 'ما الذي يحدد العلاقة في المثال؟', 'What defines the relationship in the example?', [['projects.title', 'projects.title'], ['projects.learner_id = learners.id', 'projects.learner_id = learners.id'], ['SELECT', 'SELECT'], ['name فقط', 'name only']], 1, 'جملة ON تحدد الأعمدة المرتبطة بين الجدولين.', 'The ON clause defines the linked columns between the tables.'),
    lesson('sql-5', 'السلامة ومعاملات الاستعلام', 'Safety and query parameters', 22, 'تجنب إدخال المستخدم داخل نص SQL مباشرة.', 'Avoid placing user input directly in SQL text.', 'استخدم parameterized queries مع أي بيانات خارجية؛ لا تبنِ استعلاماً بالربط النصي.', 'Use parameterized queries with external data; do not build a query with string concatenation.', 'SELECT * FROM learners\nWHERE email = ?;\n-- parameter: learner@example.com', 'لماذا نستخدم placeholder ؟', 'Why use a placeholder?', [['لفصل البيانات عن نص الاستعلام', 'To separate data from query text'], ['لإخفاء الجدول', 'To hide the table'], ['لحذف المستخدم', 'To delete the user'], ['لتغيير CSS', 'To change CSS']], 0, 'المعاملات تمنع تحويل قيمة المستخدم إلى جزء من منطق الاستعلام.', 'Parameters prevent user values from becoming part of query logic.'),
    lesson('sql-6', 'مشروع: لوحة تقدم', 'Project: progress dashboard', 30, 'تصميم استعلام يعرض تقدم المتعلم.', 'Design a query that presents learner progress.', 'لوحة البيانات الجيدة تستخدم تجميعات مفهومة وتعرض القياسات التي تقود قراراً.', 'A good dashboard uses understandable aggregations and shows measurements that drive a decision.', 'SELECT track, COUNT(*) AS completed\nFROM lesson_progress\nWHERE completed = 1\nGROUP BY track;', 'ما الذي يحسبه COUNT هنا؟', 'What does COUNT calculate here?', [['عدد الدروس المكتملة لكل مسار', 'Completed lessons per track'], ['نص المسار', 'Track text'], ['لون البطاقة', 'Card color'], ['تاريخ اليوم', 'Today’s date']], 0, 'COUNT مع GROUP BY يحسب السجلات لكل قيمة track.', 'COUNT with GROUP BY counts records for each track value.'),
  ]),
]

export const missions = [
  { id: 'mission-portfolio', title: bi('أطلق صفحة Portfolio', 'Launch a portfolio page'), track: bi('HTML/CSS + GitHub', 'HTML/CSS + GitHub'), summary: bi('ابنِ صفحة تعريف واضحة ثم انشرها مع README منظم.', 'Build a clear profile page, then publish it with a structured README.'), skills: ['HTML', 'CSS', 'Git', 'GitHub Pages'] },
  { id: 'mission-tracker', title: bi('ابنِ متعقب دراسة', 'Build a study tracker'), track: bi('Python', 'Python'), summary: bi('نظّم جلسات الدراسة واحسب مجموع الدقائق باستخدام وظائف وقوائم.', 'Organize study sessions and calculate total minutes with functions and lists.'), skills: ['Python', 'Functions', 'Lists'] },
  { id: 'mission-api', title: bi('صمّم بيانات API آمنة', 'Design safe API data'), track: bi('JavaScript + SQL', 'JavaScript + SQL'), summary: bi('مثّل بيانات المتعلم، اعرضها في الواجهة، واستخدم استعلامات بمعاملات.', 'Model learner data, present it in an interface, and use parameterized queries.'), skills: ['JavaScript', 'DOM', 'SQL', 'Security basics'] },
]
